name: Python CI

on:
  push:
    branches: [ main ]

# When this workflow is queued, automatically cancel any previous running
# or pending jobs from the same branch
concurrency:
  group: pixi-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:

    strategy:
      matrix:
        os: ["ubuntu-latest"]

    runs-on: "${{ matrix.os }}"

    steps:

    - uses: actions/checkout@v4

    - name: Setup pixi
      uses: prefix-dev/setup-pixi@v0.8.1
      with:
        pixi-version: v0.29.0
        cache: true

    - name: Review dependencies
      run: |
        pixi info
        pixi list

    - name: Test with pytest
      run: |
        pixi run zarrcade test

    - name: Upload pytest and coverage results
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: testcoverage-${{ matrix.os }}-py${{ matrix.python-version }}
        path: |
          htmlcov/*
