name: Python CI

on:
  push:
    branches: [ main ]

# When this workflow is queued, automatically cancel any previous running
# or pending jobs from the same branch
concurrency:
  group: conda-${{ github.ref }}
  cancel-in-progress: true

# Required shell entrypoint to have properly activated conda environments
defaults:
  run:
    shell: bash -l {0}

jobs:
  build:

    strategy:
      matrix:
        os: ["ubuntu-latest"]
        python-version: ["3.11"]

    runs-on: "${{ matrix.os }}"

    steps:

    - uses: actions/checkout@v4

    - name: "Cache conda"
      uses: "actions/cache@v4"
      env:
        # Increase this value to reset cache if env.yml has not changed
        CACHE_NUMBER: 0
      with:
        path: "~/conda_pkgs_dir"
        key: "${{ matrix.os }}-conda-${{ matrix.python-version }}-${{ env.CACHE_NUMBER }}-${{ hashFiles('enviroment.yml') }}"
        
    - name: Set up Python ${{ matrix.python-version }}
      uses: conda-incubator/setup-miniconda@v3
      with:
        miniforge-version: latest
        use-mamba: true
        python-version: ${{ matrix.python-version }}
        environment-file: environment.yml
        channels: conda-forge,ome
        channel-priority: strict
        activate-environment: "zarrcade"

    - name: Review dependencies
      run: |
        which python
        pip list
        mamba list

    - name: Test with pytest
      run: |
        python -m pytest -W ignore::DeprecationWarning
      #python -m pytest --cov=zarrcade --cov-report=html --cov-report=term -W ignore::DeprecationWarning --html=htmlcov/test_results.html

    - name: Upload pytest and coverage results
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: testcoverage-${{ matrix.os }}-py${{ matrix.python-version }}
        path: |
          htmlcov/*
